# Generated by Django 5.2.7 on 2025-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('WARDEN', 'Warden')], default='STUDENT', max_length=10),
        ),
    ]
